services:
   app:
     build:
       dockerfile: ./Dockerfile
     environment:
       KTOR_PORT: 8080
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
     ports:
       - "8080:8080"
